name: Terraform Plan - Dev

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        tf_version: 1.1.0

    - name: Terraform Init
      run: terraform init
      working-directory: dev  # Specify the environment directory

    - name: Terraform Plan
      run: terraform plan
      working-directory: dev  # Specify the environment directory
